/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.SinDiseno;

import Entidades.Chat;
import Entidades.Mensaje;
import Entidades.Usuario;
import Persistencia.ChatDAO;
import Persistencia.IChatDAO;
import Persistencia.IMensajeDAO;
import Persistencia.IUsuarioDAO;
import Persistencia.MensajeDAO;
import Persistencia.UsuarioDAO;
import com.mongodb.client.MongoDatabase;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.types.ObjectId;

/**
 * .
 * @author rober
 */
public class ChatsUsuario extends javax.swing.JFrame {

    private Usuario usuarioActual;
    private IChatDAO chatDAO;
    private IMensajeDAO mensajeDAO;
    private IUsuarioDAO usuarioDAO;

    /**
     * Creates new form ChatsUsuario
     */
    public ChatsUsuario(Usuario usuario, MongoDatabase db) {
        initComponents();
        this.usuarioActual = usuario;
        this.usuarioDAO = new UsuarioDAO(db);
        this.chatDAO = new ChatDAO(db);
        this.mensajeDAO = new MensajeDAO(db);

        cargarTablaChats();
    }

    /**
     * .
     */
    private void cargarTablaChats() {
        DefaultTableModel model = (DefaultTableModel) tblContactos.getModel();
        model.setRowCount(0);

        List<Chat> chats = chatDAO.obtenerChatsDeUsuario(usuarioActual.getId());

        for (Chat c : chats) {
            for (ObjectId participante : c.getParticipantes()) {
                if (!participante.equals(usuarioActual.getId())) {
                    Usuario u = usuarioDAO.obtenerPorId(participante);
                    model.addRow(new Object[]{u.getTelefono(), c.getId().toHexString()});
                }
            }
        }
    }

    /**
     * .
     * @param idChat .
     */
    private void cargarMensajes(ObjectId idChat) {
        DefaultTableModel model = (DefaultTableModel) tblMensajes.getModel();
        model.setRowCount(0);

        List<Mensaje> mensajes = mensajeDAO.obtenerMensajesDeChat(idChat);

        for (Mensaje m : mensajes) {
            Usuario emisor = usuarioDAO.obtenerPorId(m.getIdEmisor());
            model.addRow(new Object[]{
                emisor.getTelefono(),
                m.getContenido(),
                m.getFechaEnvio()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChats = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContactos = new javax.swing.JTable();
        btnBuscarMensajes = new javax.swing.JButton();
        btnCerrarSecion = new javax.swing.JButton();
        btnCrearChat = new javax.swing.JButton();
        btnCargarTabla = new javax.swing.JButton();
        pnlMensajes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMensajes = new javax.swing.JTable();
        pnlEnviarMensaje = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnEnviarMensaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlChats.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Telefono", "ID Chat"
            }
        ));
        jScrollPane1.setViewportView(tblContactos);

        btnBuscarMensajes.setText("Buscar Mensajes");
        btnBuscarMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMensajesActionPerformed(evt);
            }
        });

        btnCerrarSecion.setText("Cerrar Sesion");
        btnCerrarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSecionActionPerformed(evt);
            }
        });

        btnCrearChat.setText("Chat Nuevo");
        btnCrearChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearChatActionPerformed(evt);
            }
        });

        btnCargarTabla.setText("Cargar Tabla");
        btnCargarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChatsLayout = new javax.swing.GroupLayout(pnlChats);
        pnlChats.setLayout(pnlChatsLayout);
        pnlChatsLayout.setHorizontalGroup(
            pnlChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChatsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnCerrarSecion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addComponent(btnBuscarMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(pnlChatsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnCrearChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(btnCargarTabla)
                .addGap(34, 34, 34))
        );
        pnlChatsLayout.setVerticalGroup(
            pnlChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChatsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearChat)
                    .addComponent(btnCargarTabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarMensajes)
                    .addComponent(btnCerrarSecion))
                .addGap(21, 21, 21))
        );

        pnlMensajes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblMensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Telefono", "Mensaje", "Fecha"
            }
        ));
        jScrollPane2.setViewportView(tblMensajes);

        javax.swing.GroupLayout pnlMensajesLayout = new javax.swing.GroupLayout(pnlMensajes);
        pnlMensajes.setLayout(pnlMensajesLayout);
        pnlMensajesLayout.setHorizontalGroup(
            pnlMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMensajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        pnlMensajesLayout.setVerticalGroup(
            pnlMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMensajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlEnviarMensaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        btnEnviarMensaje.setText("Mandar Mensaje");
        btnEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMensajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEnviarMensajeLayout = new javax.swing.GroupLayout(pnlEnviarMensaje);
        pnlEnviarMensaje.setLayout(pnlEnviarMensajeLayout);
        pnlEnviarMensajeLayout.setHorizontalGroup(
            pnlEnviarMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnviarMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(pnlEnviarMensajeLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(btnEnviarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(264, 264, 264))
        );
        pnlEnviarMensajeLayout.setVerticalGroup(
            pnlEnviarMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnviarMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviarMensaje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlChats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEnviarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlEnviarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlChats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMensajesActionPerformed
        int fila = tblContactos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un chat primero");
            return;
        }

        String idChatString = tblContactos.getValueAt(fila, 1).toString();
        ObjectId idChat = new ObjectId(idChatString);
        cargarMensajes(idChat);
    }//GEN-LAST:event_btnBuscarMensajesActionPerformed

    private void btnEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMensajeActionPerformed
        int fila = tblContactos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un chat primero");
            return;
        }

        String texto = jTextArea1.getText().trim();
        if (texto.isEmpty()) {
            return;
        }

        String idChatString = tblContactos.getValueAt(fila, 1).toString();
        ObjectId idChat = new ObjectId(idChatString);

        Mensaje msg = new Mensaje(usuarioActual.getId(), texto, new Date());
        mensajeDAO.insertar(idChat, msg);

        jTextArea1.setText("");
        cargarMensajes(idChat); // refrescar
    }//GEN-LAST:event_btnEnviarMensajeActionPerformed

    private void btnCrearChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearChatActionPerformed
        AgregarChat ventana = new AgregarChat(usuarioActual, usuarioDAO, chatDAO);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnCrearChatActionPerformed

    private void btnCerrarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSecionActionPerformed
        dispose();
        Main m = new Main();
        m.setVisible(true);
    }//GEN-LAST:event_btnCerrarSecionActionPerformed

    private void btnCargarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTablaActionPerformed
        cargarTablaChats();
    }//GEN-LAST:event_btnCargarTablaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChatsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChatsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChatsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChatsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() Maid Kyouiku. Botsuraku Kizoku Rurikawa Tsubaki The Animation{
//            public void run() {
//                new ChatsUsuario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMensajes;
    private javax.swing.JButton btnCargarTabla;
    private javax.swing.JButton btnCerrarSecion;
    private javax.swing.JButton btnCrearChat;
    private javax.swing.JButton btnEnviarMensaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnlChats;
    private javax.swing.JPanel pnlEnviarMensaje;
    private javax.swing.JPanel pnlMensajes;
    private javax.swing.JTable tblContactos;
    private javax.swing.JTable tblMensajes;
    // End of variables declaration//GEN-END:variables
}
