/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Chat;
import Entidades.Usuario;
import Persistencia.IChatDAO;
import Persistencia.IUsuarioDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.bson.types.ObjectId;

/**
 *
 * @author Angel Servin
 */
public class AC extends javax.swing.JFrame {    // esta clase seria AgregarChat

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AC.class.getName());
    private Usuario usuarioActual;
    private IUsuarioDAO udao;
    private IChatDAO cdao;

    /**
     * Creates new form AC
     */
    public AC(Usuario usuarioActual, IUsuarioDAO udao, IChatDAO cdao) {
        initComponents();
        this.usuarioActual = usuarioActual;
        this.udao = udao;
        this.cdao = cdao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        txtNumeroTelefono = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/btnVolver.png"))); // NOI18N
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setDefaultCapable(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        txtNumeroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumeroTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 82, 130, 20));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/btnAgregar.png"))); // NOI18N
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setDefaultCapable(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/AgregarChat.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String telefonoNuevo = txtNumeroTelefono.getText().trim();

        if (telefonoNuevo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido");
            return;
        }

        Usuario usuarioNuevo = udao.obtenerPorTelefono(telefonoNuevo);

        if (usuarioNuevo == null) {
            JOptionPane.showMessageDialog(this, "El usuario no existe en la base de datos");
            return;
        }

        if (usuarioNuevo.getId().equals(usuarioActual.getId())) {
            JOptionPane.showMessageDialog(this, "No puedes crear un chat contigo mismo");
            return;
        }

        Chat chatExistente = cdao.obtenerChatPorParticipantes(usuarioActual.getId(), usuarioNuevo.getId());
        if (chatExistente != null) {
            JOptionPane.showMessageDialog(this, "Ya existe un chat con ese usuario");
            return;
        }

        List<ObjectId> participantes = new ArrayList<>();
        participantes.add(usuarioActual.getId());
        participantes.add(usuarioNuevo.getId());

        Chat nuevoChat = new Chat(participantes);
        cdao.insertar(nuevoChat);

        JOptionPane.showMessageDialog(this, "Chat creado correctamente");
        dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtNumeroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTelefonoActionPerformed
        txtNumeroTelefono.setForeground(txtNumeroTelefono.getBackground());
        txtNumeroTelefono.setCaretColor(txtNumeroTelefono.getBackground());
        txtNumeroTelefono.setBorder(null);
    }//GEN-LAST:event_txtNumeroTelefonoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNumeroTelefono;
    // End of variables declaration//GEN-END:variables
}
