/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Direccion;
import Entidades.Usuario;
import Persistencia.ConexionMongo;
import Persistencia.UsuarioDAO;
import Utilidades.Validaciones;
import com.mongodb.client.MongoDatabase;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.bson.types.ObjectId;

/**
 *
 * @author Angel Servin
 */
public class AgregarUsuarioChilo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarUsuarioChilo.class.getName());

    /**
     * Creates new form AgregarUsuarioChilo
     */
    public AgregarUsuarioChilo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnCrearCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTelefono.setBackground(new java.awt.Color(217, 217, 217));
        txtTelefono.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 102, 128, -1));

        txtSexo.setBackground(new java.awt.Color(217, 217, 217));
        txtSexo.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 131, 128, 20));

        txtFechaNacimiento.setBackground(new java.awt.Color(217, 217, 217));
        txtFechaNacimiento.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 156, 128, 20));

        txtCalle.setBackground(new java.awt.Color(217, 217, 217));
        txtCalle.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleActionPerformed(evt);
            }
        });
        jPanel1.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 181, 128, -1));

        txtColonia.setBackground(new java.awt.Color(217, 217, 217));
        txtColonia.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColoniaActionPerformed(evt);
            }
        });
        jPanel1.add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 208, 128, 20));

        txtCiudad.setBackground(new java.awt.Color(217, 217, 217));
        txtCiudad.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 234, 128, 20));

        txtContrasena.setBackground(new java.awt.Color(217, 217, 217));
        txtContrasena.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 261, 128, 20));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVolver.png"))); // NOI18N
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setDefaultCapable(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        btnCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCrearCuenta.png"))); // NOI18N
        btnCrearCuenta.setBorderPainted(false);
        btnCrearCuenta.setContentAreaFilled(false);
        btnCrearCuenta.setDefaultCapable(false);
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AgregarUsuario.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleActionPerformed

    private void txtColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColoniaActionPerformed

    private void txtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
        MainChilo m = new MainChilo();
        m.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        try {
            String telefono = txtTelefono.getText().trim();
            String password = txtContrasena.getText().trim();
            String sexo = txtSexo.getText().trim();
            String fechaStr = txtFechaNacimiento.getText().trim();
            String calle = txtCalle.getText().trim();
            String colonia = txtColonia.getText().trim();
            String ciudad = txtCiudad.getText().trim();

            // Validar Espacios Vacios
            if (telefono.isEmpty() || password.isEmpty() || sexo.isEmpty()
                    || fechaStr.isEmpty() || calle.isEmpty() || colonia.isEmpty() || ciudad.isEmpty()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Todos los campos son obligatorios.",
                        "Campos incompletos y/o vacios",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // Validar Telefono
            if (!Validaciones.validarTelefono(telefono)) {
                JOptionPane.showMessageDialog(
                        this,
                        "El telefono debe contener exactamente 10 digitos.",
                        "Telefono invalido",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // Validar Contrasenia
            if (!Validaciones.validarPassword(password)) {
                JOptionPane.showMessageDialog(
                        this,
                        "La contraseña debe tener 8 caracteres minimo, incluir letras y números.",
                        "Contraseña invalida",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // Validar Sexo
            if (!sexo.equalsIgnoreCase("M") && !sexo.equalsIgnoreCase("H")) {
                JOptionPane.showMessageDialog(
                        this,
                        "El sexo solo puede ser 'M' (Mujer) o 'H' (Hombre).",
                        "Sexo invalido",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // Validar Fecha de Nacimiento
            Date fechaNacimiento;
            try {
                fechaNacimiento = java.sql.Date.valueOf(fechaStr); // formato yyyy-mm-dd
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "La fecha debe tener el formato YYYY-MM-DD.",
                        "Fecha invalida",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            Direccion direccion = new Direccion(calle, colonia, ciudad);
            List<ObjectId> chats = new ArrayList<>();
            Usuario usuario = new Usuario(telefono, password, sexo, fechaNacimiento, direccion, chats);
            MongoDatabase db = ConexionMongo.conectar();
            UsuarioDAO usuarioDAO = new UsuarioDAO(db);
            usuarioDAO.insertar(usuario);

            JOptionPane.showMessageDialog(
                    this,
                    "Usuario creado.",
                    "Registro completado",
                    JOptionPane.INFORMATION_MESSAGE
            );

            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + ex.getMessage(),
                    "Error inesperado",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
