/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Chat;
import Entidades.Usuario;
import Persistencia.IChatDAO;
import Persistencia.IUsuarioDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import org.bson.types.ObjectId;

/**
 *
 * @author Angel Servin
 */
public class AgregarChatChilo extends javax.swing.JFrame {

    private Usuario usuarioActual;
    private IUsuarioDAO udao;
    private IChatDAO cdao;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarChatChilo.class.getName());

    /**
     * Creates new form AgregarChatChilo
     */
    public AgregarChatChilo(Usuario usuarioActual, IUsuarioDAO udao, IChatDAO cdao) {
        initComponents();
        this.usuarioActual = usuarioActual;
        this.udao = udao;
        this.cdao = cdao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtNumeroTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAgregar.png"))); // NOI18N
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setDefaultCapable(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVolver.png"))); // NOI18N
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setDefaultCapable(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        txtNumeroTelefono.setBackground(new java.awt.Color(217, 217, 217));
        txtNumeroTelefono.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtNumeroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumeroTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 129, 18));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AgregarChat.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String telefonoNuevo = txtNumeroTelefono.getText().trim();

        if (telefonoNuevo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de teléfono válido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Usuario usuarioNuevo = udao.obtenerPorTelefono(telefonoNuevo);
        if (usuarioNuevo == null) {
            JOptionPane.showMessageDialog(this, "El usuario no existe en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (usuarioNuevo.getId().equals(usuarioActual.getId())) {
            JOptionPane.showMessageDialog(this, "No puedes crear un chat contigo mismo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Chat chatExistente = cdao.obtenerChatPorParticipantes(usuarioActual.getId(), usuarioNuevo.getId());
        if (chatExistente != null) {
            JOptionPane.showMessageDialog(this, "Ya existe un chat con ese usuario.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            List<ObjectId> participantes = new ArrayList<>();
            participantes.add(usuarioActual.getId());
            participantes.add(usuarioNuevo.getId());
            Chat nuevoChat = new Chat(participantes);
            cdao.insertar(nuevoChat);
            JOptionPane.showMessageDialog(this, "Chat creado correctamente con " + usuarioNuevo.getTelefono(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error al crear el chat", e);
            JOptionPane.showMessageDialog(this, "Ocurrió un error al crear el chat.", "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNumeroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTelefonoActionPerformed
        btnAgregarActionPerformed(evt);
    }//GEN-LAST:event_txtNumeroTelefonoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtNumeroTelefono;
    // End of variables declaration//GEN-END:variables
}
