/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Direccion;
import Entidades.Usuario;
import Persistencia.ConexionMongo;
import Persistencia.UsuarioDAO;
import com.mongodb.client.MongoDatabase;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.bson.types.ObjectId;

/**
 *
 * @author Angel Servin
 */
public class AU extends javax.swing.JFrame { //esta clase seria agregarUsuario

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AU.class.getName());

    /**
     * Creates new form AU
     */
    public AU() {
        initComponents();
        hacerInvisibles();
    }

    private void hacerInvisibles() {

        // SEXO
        txtSexo.setForeground(txtSexo.getBackground());
        txtSexo.setCaretColor(txtSexo.getBackground());
        txtSexo.setBorder(null);

        // TELEFONO
        txtTelefono.setForeground(txtTelefono.getBackground());
        txtTelefono.setCaretColor(txtTelefono.getBackground());
        txtTelefono.setBorder(null);

        // FECHA NACIMIENTO
        txtFechaNacimiento.setForeground(txtFechaNacimiento.getBackground());
        txtFechaNacimiento.setCaretColor(txtFechaNacimiento.getBackground());
        txtFechaNacimiento.setBorder(null);

        // CONTRASEÑA
        txtContraseña.setForeground(txtContraseña.getBackground());
        txtContraseña.setCaretColor(txtContraseña.getBackground());
        txtContraseña.setBorder(null);

        // CIUDAD
        txtCiudad.setForeground(txtCiudad.getBackground());
        txtCiudad.setCaretColor(txtCiudad.getBackground());
        txtCiudad.setBorder(null);

        // COLONIA
        txtColonia.setForeground(txtColonia.getBackground());
        txtColonia.setCaretColor(txtColonia.getBackground());
        txtColonia.setBorder(null);

        // CALLE
        txtCalle.setForeground(txtCalle.getBackground());
        txtCalle.setCaretColor(txtCalle.getBackground());
        txtCalle.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSexo = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        btnCrearCuenta = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 140, 10));

        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, 10));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 140, 10));

        txtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleActionPerformed(evt);
            }
        });
        jPanel1.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 192, 140, 10));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 130, 10));

        txtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 242, 130, 10));

        txtColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColoniaActionPerformed(evt);
            }
        });
        jPanel1.add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 140, 10));

        btnCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/btnCrearCuenta.png"))); // NOI18N
        btnCrearCuenta.setBorderPainted(false);
        btnCrearCuenta.setContentAreaFilled(false);
        btnCrearCuenta.setDefaultCapable(false);
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/btnVolver.png"))); // NOI18N
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setDefaultCapable(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/AgregarUsuario.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed

     }//GEN-LAST:event_txtSexoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed

     }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed

     }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        try {
            // Obtener valores del formulario
            String telefono = txtTelefono.getText();
            String password = txtContraseña.getText();
            String sexo = txtSexo.getText();
            String fechaStr = txtFechaNacimiento.getText();
            String calle = txtCalle.getText();
            String colonia = txtColonia.getText();
            String ciudad = txtCiudad.getText();

            // Validaciones básicas
            if (telefono.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe llenar teléfono y contraseña.");
                return;
            }

            // Convertir fecha
            Date fechaNacimiento = java.sql.Date.valueOf(fechaStr);

            // Crear objeto Dirección
            Direccion direccion = new Direccion(calle, colonia, ciudad);

            // Crear lista vacía para chats
            List<ObjectId> chats = new ArrayList<>();

            // Crear Usuario
            Usuario usuario = new Usuario(telefono, password, sexo, fechaNacimiento, direccion, chats);

            // Llamar DAO para insertar
            MongoDatabase db = ConexionMongo.conectar();
            UsuarioDAO usuarioDAO = new UsuarioDAO(db);
            usuarioDAO.insertar(usuario);

            JOptionPane.showMessageDialog(this, "Usuario creado exitosamente!");
            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void txtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadActionPerformed

    private void txtColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColoniaActionPerformed

    private void txtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
