/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Chat;
import Entidades.Mensaje;
import Entidades.Usuario;
import Persistencia.ChatDAO;
import Persistencia.IChatDAO;
import Persistencia.IMensajeDAO;
import Persistencia.IUsuarioDAO;
import Persistencia.MensajeDAO;
import Persistencia.UsuarioDAO;
import com.mongodb.client.MongoDatabase;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.types.ObjectId;

/**
 *
 * @author Angel Servin
 */
public class CU extends javax.swing.JFrame {  //esta clase seria ChatUsuario

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CU.class.getName());
    private Usuario usuarioActual;
    private IChatDAO chatDAO;
    private IMensajeDAO mensajeDAO;
    private IUsuarioDAO usuarioDAO;

    public CU(Usuario usuario, MongoDatabase db) {
        initComponents();
        this.usuarioActual = usuario;
        this.usuarioDAO = new UsuarioDAO(db);
        this.chatDAO = new ChatDAO(db);
        this.mensajeDAO = new MensajeDAO(db);

        cargarTablaChats();
    }

    private void cargarTablaChats() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        List<Chat> chats = chatDAO.obtenerChatsDeUsuario(usuarioActual.getId());

        for (Chat c : chats) {
            for (ObjectId participante : c.getParticipantes()) {
                if (!participante.equals(usuarioActual.getId())) {
                    Usuario u = usuarioDAO.obtenerPorId(participante);
                    model.addRow(new Object[]{u.getTelefono(), c.getId().toHexString()});
                }
            }
        }
    }

    private void cargarMensajes(ObjectId idChat) {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        List<Mensaje> mensajes = mensajeDAO.obtenerMensajesDeChat(idChat);

        for (Mensaje m : mensajes) {
            Usuario emisor = usuarioDAO.obtenerPorId(m.getIdEmisor());
            model.addRow(new Object[]{
                emisor.getTelefono(),
                m.getContenido(),
                m.getFechaEnvio()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnChatNuevo = new javax.swing.JButton();
        btnCargarTabla = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnBuscarMensajes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnMandarMensajes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Telefono", "ID Chat"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, 480));

        btnChatNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/btnChatNuevo.png"))); // NOI18N
        btnChatNuevo.setBorderPainted(false);
        btnChatNuevo.setContentAreaFilled(false);
        btnChatNuevo.setDefaultCapable(false);
        btnChatNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnChatNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnCargarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/btnCargarTabla.png"))); // NOI18N
        btnCargarTabla.setBorderPainted(false);
        btnCargarTabla.setContentAreaFilled(false);
        btnCargarTabla.setDefaultCapable(false);
        btnCargarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTablaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/btnCerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setDefaultCapable(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        btnBuscarMensajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/btnBuscarMensajes.png"))); // NOI18N
        btnBuscarMensajes.setBorderPainted(false);
        btnBuscarMensajes.setContentAreaFilled(false);
        btnBuscarMensajes.setDefaultCapable(false);
        btnBuscarMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMensajesActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Telefono", "Mensaje", "Fecha"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 580, 390));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 580, -1));

        btnMandarMensajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/btnMandarMensaje.png"))); // NOI18N
        btnMandarMensajes.setBorderPainted(false);
        btnMandarMensajes.setContentAreaFilled(false);
        btnMandarMensajes.setDefaultCapable(false);
        btnMandarMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMandarMensajesActionPerformed(evt);
            }
        });
        jPanel1.add(btnMandarMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/ChatUsuario.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMandarMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMandarMensajesActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un chat primero");
            return;
        }

        String texto = jTextArea1.getText().trim();
        if (texto.isEmpty()) {
            return;
        }

        String idChatString = jTable1.getValueAt(fila, 1).toString();
        ObjectId idChat = new ObjectId(idChatString);

        Mensaje msg = new Mensaje(usuarioActual.getId(), texto, new Date());
        mensajeDAO.insertar(idChat, msg);

        jTextArea1.setText("");
        cargarMensajes(idChat);
    }//GEN-LAST:event_btnMandarMensajesActionPerformed

    private void btnBuscarMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMensajesActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un chat primero");
            return;
        }

        String idChatString = jTable1.getValueAt(fila, 1).toString();
        ObjectId idChat = new ObjectId(idChatString);
        cargarMensajes(idChat);
    }//GEN-LAST:event_btnBuscarMensajesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        dispose();
        Main m = new Main();
        m.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnChatNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatNuevoActionPerformed
        AgregarChat ventana = new AgregarChat(usuarioActual, usuarioDAO, chatDAO);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnChatNuevoActionPerformed

    private void btnCargarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTablaActionPerformed
        cargarTablaChats();

    }//GEN-LAST:event_btnCargarTablaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMensajes;
    private javax.swing.JButton btnCargarTabla;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnChatNuevo;
    private javax.swing.JButton btnMandarMensajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
