/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Usuario;
import Persistencia.ConexionMongo;
import Persistencia.IUsuarioDAO;
import Persistencia.UsuarioDAO;
import Utilidades.Validaciones;
import com.mongodb.client.MongoDatabase;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/**
 * Ventana del inicio de sesion.
 * @author Roberto Verdugo y Angel Servin
 */
public class MainChilo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainChilo.class.getName());
    MongoDatabase db = ConexionMongo.conectar();

    /**
     * Creates new form MainChilo
     */
    public MainChilo() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        btnCrearCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTelefono.setBackground(new java.awt.Color(217, 217, 217));
        txtTelefono.setForeground(new java.awt.Color(51, 51, 51));
        txtTelefono.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 128, 20));

        txtContraseña.setBackground(new java.awt.Color(217, 217, 217));
        txtContraseña.setForeground(new java.awt.Color(51, 51, 51));
        txtContraseña.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 128, -1));

        btnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnIniciarSesion.png"))); // NOI18N
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.setContentAreaFilled(false);
        btnIniciarSesion.setDefaultCapable(false);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        btnCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCrearCuenta.png"))); // NOI18N
        btnCrearCuenta.setBorderPainted(false);
        btnCrearCuenta.setContentAreaFilled(false);
        btnCrearCuenta.setDefaultCapable(false);
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Main.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para iniciar sesion
     *
     * @param evt .
     */
    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        IUsuarioDAO udao = new UsuarioDAO(db);

        String telefono = txtTelefono.getText().trim();
        String contrasena = txtContraseña.getText().trim();

        // Validar Telefono
        if (!Validaciones.validarTelefono(telefono)) {
            JOptionPane.showMessageDialog(
                    this,
                    "El teléfono debe contener exactamente 10 dígitos numéricos.",
                    "Teléfono inválido",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Validar Contrasenia
        if (!Validaciones.validarPassword(contrasena)) {
            JOptionPane.showMessageDialog(
                    this,
                    "La contrasenia debe tener 8 caracteres minimo, incluir letras y numeros.",
                    "Contrasenia incorrecta.",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Iniciar Sesion
        try {
            boolean resultado = udao.iniciarSesion(telefono, contrasena);

            if (resultado) {
                JOptionPane.showMessageDialog(
                        this,
                        "Bienvenido",
                        "Inicio de Sesion Exitoso",
                        JOptionPane.INFORMATION_MESSAGE
                );

                Usuario usuarioActual = udao.obtenerPorTelefono(telefono);
                ChatsUsuarioChilo cu = new ChatsUsuarioChilo(usuarioActual, db);
                cu.setVisible(true);
                dispose();

            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Usuario o Contrasenia Incorrectos",
                        "Error de Autenticacion",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Error al intentar iniciar sesion", ex);
            JOptionPane.showMessageDialog(
                    this,
                    "Ocurrio un error inesperado al conectar.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * Metodo para entar a la ventana de agregar cuenta
     *
     * @param evt .
     */
    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        AgregarUsuarioChilo au = new AgregarUsuarioChilo();
        au.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainChilo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
